import Head from "next/head";
import Image from "next/image";

import { Navbar } from "@/components";
import { Hero } from "@/sections";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />

        <div className='nav-h px-[20px]'>
          <Hero />
        </div>
      </main>
    </>
  );
}
