import React, { useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import Web3 from "web3";

import { useRouter } from "next/router";

import { Form, Modal } from "@/components";
import { Hero } from "@/sections";
import CreateMeetContext from "@/context/MeetContext";
import { shortenAddress } from "@/utils/shortenAddr";

import { Navbar, Info } from "@/components";
import Background from "@/components/Background";

export default function Home() {
  const {
    address,
    setAddress,
    toggleModal,
    setToggleModal,
    checkNftBalance,
    connectWallet,
  } = useContext(CreateMeetContext);

  const router = useRouter();

  const checkNftAuth = async () => {
    const response = await checkNftBalance();

    if (response) {
      router.push("/explore");
    } else {
      alert("Please register before proceeding!!");
    }
  };

  return (
    <div>
      {/* <Navbar explore /> */}
      <Head>
        <title>InfoBase</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative'>
        {toggleModal && (
          <div className='fixed z-50 top-0 bottom-0 left-0 right-0 w-[100vw] h-[100vh] flex items-center justify-center bg-gray-600 bg-opacity-10 backdrop-filter backdrop-blur-lg'>
            <Modal />
          </div>
        )}

        <div className='h-[100vh] px-[20px] z-30'>
          <div className='absolute left-[20px] top-[20px] z-20'>
            <p className='z-30 text-white'>InfoBase</p>
          </div>

          <div className='absolute right-[20px] top-[20px] space-x-4 z-30'>
            <button
              className='btn btn-outline border-[2px] px-[30px] text-[14px] border-[#950740] text-[#c3073f] hover:bg-[#950740] hover:border-[#950740] hover:text-[#1a1a1d] z-30'
              onClick={() => checkNftAuth()}
            >
              Sign In
            </button>
            {address !== "" ? (
              <button className='text-white btn btn-outline border-[2px] px-[30px] text-[14px] border-[#950740] hover:bg-[#950740] hover:border-[#950740] hover:text-[#1a1a1d] z-30'>
                {shortenAddress(address)}
              </button>
            ) : (
              <button
                className='btn btn-outline border-[2px] px-[30px] text-[14px] border-[#950740] text-[#c3073f] hover:bg-[#950740] hover:border-[#950740] hover:text-[#1a1a1d] z-30'
                onClick={() => connectWallet()}
              >
                connect wallet
              </button>
            )}
          </div>

          <div className='flex'>
            <div className='flex-1 z-40 mt-[120px]'>joy</div>
            <div className='flex-1 z-40 mt-[120px] flex items-center justify-center '>
              <Form />
            </div>
          </div>
        </div>

        <div className='absolute top-0 bottom-0 right-0 left-0'>
          <Background />
        </div>
      </main>
    </div>
  );
}
